### ISSUE TITLE
tanya

### ISSUE THREAD

**Issue by luqmanfajar** [Widiskel/tabizoo-mining-bot#1]
"app_id": 6,
    "app_hash": "eb06d4abfb49dc3eeb1aeb98ae0f581e",
    "device": "Xiaomi Mi Max 2",
    "sdk": "SDK 31",
    "app_version": "10.13.4 (48552)",
    "system_lang_code": "en-us",
    "lang_pack": "android",
    "lang_code": "en",
    "session_file": "12176181615",
    "phone": "12176181615",
    "first_name": "Juniper",
    "last_name": "Gugliotta"
    
    file session.json seperti ini bisa dipakai kah bang

**Comment by Widiskel** [comment]
dpt drmna itu bg

**Comment by Widiskel** [comment]
sessions di bot gw biasanya gni bg
<img width="237" alt="Screenshot 2024-07-11 at 15 14 56" src="https://github.com/Widiskel/tabizoo-mining-bot/assets/97203329/db7a8b7d-5c14-4452-8985-672c3167bad9">

**Comment by luqmanfajar** [comment]
oh beda berarti
