### ISSUE TITLE
Your tool can't run multi accounts?

### ISSUE THREAD

**Issue by skypeleft** [Widiskel/tabizoo-mining-bot#4]
Your tool can't run multi accounts?.
I've created 2 session, but it's run 1 account

**Comment by Widiskel** [comment]
The bot CLI initerface is using twisters , so it only show based on your terminal screen size, try to adjust your terminal size and it showed up, don't worry it run multiple account, it just not showed up
<img width="404" alt="Screenshot 2024-07-19 at 13 14 56" src="https://github.com/user-attachments/assets/9725f440-fa15-4f06-90be-cac9c3b80527">

**Comment by skypeleft** [comment]
Pro, can i contact you on telegram?
